//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWhale.Extensions.Consuls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenWhale.Extensions.Consuls.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数不可为空.
        /// </summary>
        public static string argument_can_not_be_null_or_empty {
            get {
                return ResourceManager.GetString("argument can not be null or empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用iis可能出现该异常，如果要使用iis则必须手动指定本机的地址和端口，否则本机端口和地址可以为空.
        /// </summary>
        public static string maybe_you_use_iisexpress {
            get {
                return ResourceManager.GetString("maybe you use iisexpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务断开时间{0}.
        /// </summary>
        public static string opening_time {
            get {
                return ResourceManager.GetString("opening time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务由于异常被迫断开.
        /// </summary>
        public static string service_has_borken_down {
            get {
                return ResourceManager.GetString("service has borken down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务处于版开启状态.
        /// </summary>
        public static string service_is_half_open {
            get {
                return ResourceManager.GetString("service is half open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务连接到consul服务器，请检查consul服务是否启用，防火墙是否允许.
        /// </summary>
        public static string unable_connect_to_consul {
            get {
                return ResourceManager.GetString("unable connect to consul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你必须先添加Polly服务.
        /// </summary>
        public static string you_must_add_polly_first {
            get {
                return ResourceManager.GetString("you must add polly first", resourceCulture);
            }
        }
    }
}
